site_name: Firmware HQ
site_description: Documentation of the Firmware HQ SDK
edit_uri: https://github.com/Firmware-HQ/Firmware-HQ/blob/main/docs/
theme: 
  name: readthedocs
  analytics:
    gtag: G-CLYDY54S4B
nav:
  - index.md
markdown_extensions:
  - toc:
      permalink: ""
      baselevel: 2
      separator: "_"
